apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage Developer Portal für APIs
  annotations:
    github.com/project-slug: adessowan/backstage
spec:
  type: service
  lifecycle: production
  owner: default-team

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: autobahn-api
  description: API für Autobahn-Daten
  annotations:
    github.com/project-slug: adessowan/backstage
    backstage.io/api-linter: spectral
spec:
  type: openapi
  lifecycle: production
  owner: default-team
  definition:
    $text: https://raw.githubusercontent.com/adessowan/backstage/refs/heads/main/autobahn.yaml?token=GHSAT0AAAAAAC7KVX5DWZPYXTTJ7O37OGFOZ6YB6FA

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dwd-api
  description: API für Wetterdaten (DWD)
  annotations:
    github.com/project-slug: adessowan/backstage
    backstage.io/api-linter: spectral
spec:
  type: openapi
  lifecycle: production
  owner: default-team
  definition:
    $text: https://raw.githubusercontent.com/adessowan/backstage/refs/heads/main/dwd.yaml?token=GHSAT0AAAAAAC7KVX5DZJ4XYI2SFZSLGBUKZ6YB7CA

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ladesaeulen-api
  description: API für Ladesäulen-Daten
  annotations:
    github.com/project-slug: adessowan/backstage
    backstage.io/api-linter: spectral
spec:
  type: openapi
  lifecycle: production
  owner: default-team
  definition:
    $text: https://raw.githubusercontent.com/adessowan/backstage/refs/heads/main/ladesaeulen.yaml?token=GHSAT0AAAAAAC7KVX5D3W7M4363YQORMK2KZ6YB7UQ
